name: Go lint

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go ^1.14
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      
    - name: Tidy
      run: go mod tidy && [ -z "$(git status -s)" ]

    - name: Lint
      run: make lint

    - name: Vet
      run: make vet