name: Go test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{matrix.platform}}
    env:
      LLVL: trace
    steps:
    - name: Set up Go ^1.14
      uses: actions/setup-go@v2
      with:
        go-version: ^1.14
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
      
    - name: Test with coverage
      if: matrix.platform == 'ubuntu-latest'
      run: go test -covermode=count -coverprofile=profile.cov ./...

    - name: Test without coverage
      if: matrix.platform == 'macos-latest' || matrix.platform == 'windows-latest'
      run: go test ./...

    - name: Send coverage
      if: matrix.platform == 'ubuntu-latest'
      uses: shogo82148/actions-goveralls@v1
      with:
        path-to-profile: profile.cov
        parallel: true
        
  # notifies that all test jobs are finished.
  finish:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: shogo82148/actions-goveralls@v1
        with:
          parallel-finished: true
